import type { Metadata } from "next";
import "./globals.css";
import DashboardWrapper from "./dashboarWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  /** pass a Children to DashboardWrapper component */
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
